linker_redirect:
    defaults: { _controller: LinkerBundle:Redirect:index }
    path:     /{id}
linker_link:
    resource: "@LinkerBundle/Resources/config/routing/link.yml"
    prefix:   /link
linker_homepage:
    path:     /
    defaults: { _controller: LinkerBundle:Link:new }
