<?php

namespace LinkerBundle\Repository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOutdatedLinks(\DateTime $dateLimit)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('l')
            ->from('LinkerBundle:Link', 'l')
            ->where('l.createdAt < :dateLimit')
            ->setParameter('dateLimit', $dateLimit)
        ;

        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
