link_index:
    path:     /
    defaults: { _controller: "LinkerBundle:Link:index" }
    methods:  GET

link_show:
    path:     /{id}/show
    defaults: { _controller: "LinkerBundle:Link:show" }
    methods:  GET

link_new:
    path:     /new
    defaults: { _controller: "LinkerBundle:Link:new" }
    methods:  [GET, POST]

link_newpost:
    path:     /newpost
    defaults: { _controller: "LinkerBundle:Link:newpost" }
    methods:  [GET,POST]

#link_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "v:Links:edit" }
#    methods:  [GET, POST]
#
link_delete:
    path:     /{id}/delete
    defaults: { _controller: "LinkerBundle:Link:delete" }
    methods:  DELETE
